import type { Metadata } from "next";
import "./globals.css";
import {Providers} from "@/components/my-ui/providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen w-screen">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
