import type { Metadata } from "next";
import "./globals.css";
import {Providers} from "@/components/my-ui/providers";
import {ConvexClientProvider} from "@/components/ConvexClientProvider";
import {getToken} from "@/lib/auth-server";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getToken();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen w-screen">
        <Providers>
          <ConvexClientProvider initialToken={token}>
            {children}
          </ConvexClientProvider>
        </Providers>
      </body>
    </html>
  );
}
